db:
  type: postgres
  user: arisawiki_db_hsoa_user
  host: dpg-d04h3ch5pdvs73cbuod0-a
  port: 5432
  database: arisawiki_db_hsoa
  password: o1o4soGOAr8SWDfUydm5ExO7BPn2Pl3X
  ssl: true

server:
  host: 0.0.0.0
  port: 10000
  protocol: http
